"""Default values, paths, and symbols."""

from .auth import BROWSER_AUTO
from .formats import QUALITY_BEST

# ===== PLATFORM NAMES =====
PLATFORM_YOUTUBE = "YouTube"
PLATFORM_ODYSEE = "Odysee"
PLATFORM_GENERIC = "Generic"

# ===== DEFAULT VALUES =====
DEFAULT_AUDIO_CODEC = "mp3"
DEFAULT_AUDIO_QUALITY = "192"
DEFAULT_VIDEO_QUALITY = QUALITY_BEST
DEFAULT_BROWSER_PREFERENCE = BROWSER_AUTO
DEFAULT_OUTPUT_DIR = "~/Downloads"

# ===== WINDOW SIZES =====
MAIN_WINDOW_MIN_WIDTH = 900
MAIN_WINDOW_MIN_HEIGHT = 850
PREFERENCES_WINDOW_MIN_WIDTH = 550
PREFERENCES_WINDOW_MIN_HEIGHT = 350

# ===== ICON SIZES =====
ICON_BANNER_SIZE = 60
ICON_SPLASH_SIZE = 400

# ===== DOCUMENTATION PATHS =====
DOCS_FOLDER = "docs"
DOC_README = f"{DOCS_FOLDER}/README.md"
DOC_GETTING_STARTED = f"{DOCS_FOLDER}/GETTING_STARTED.md"
DOC_AUTHENTICATION = f"{DOCS_FOLDER}/AUTHENTICATION_GUIDE.md"
DOC_SECURITY = f"{DOCS_FOLDER}/SECURITY_AND_PRIVACY.md"
DOC_ARCHITECTURE = f"{DOCS_FOLDER}/ARCHITECTURE.md"
DOC_CHANGELOG = "CHANGELOG.md"

# ===== URLs =====
URL_YOUTUBE = "https://www.youtube.com"
URL_GITHUB_REPO = "https://github.com/asafelobotomy/AV-Morning-Star"

# ===== EMOJI/SYMBOLS (for consistency) =====
SYMBOL_CHECK = "✓"
SYMBOL_CROSS = "✗"
SYMBOL_WARNING = "⚠"
SYMBOL_INFO = "ℹ"
SYMBOL_SUCCESS = "✅"
SYMBOL_ERROR = "❌"
SYMBOL_QUESTION = "❓"
SYMBOL_LIGHTBULB = "💡"
