"""AV Morning Star constants."""

# ===== DOWNLOAD MODES =====
MODE_BASIC = "basic"
MODE_ADVANCED = "advanced"
MODE_BASIC_LABEL = "Basic (Auto-detect best quality)"
MODE_ADVANCED_LABEL = "Advanced (Manual settings)"

# ===== FORMAT TYPES =====
FORMAT_VIDEO = "Video"
FORMAT_AUDIO_ONLY = "Audio Only"
FORMAT_TYPE_VIDEO = "video"
FORMAT_TYPE_AUDIO = "audio"

# ===== VIDEO QUALITIES =====
QUALITY_BEST = "Best"
QUALITY_4K = "4K (2160p)"
QUALITY_1440P = "1440p"
QUALITY_1080P = "1080p"
QUALITY_720P = "720p"
QUALITY_480P = "480p"
QUALITY_360P = "360p"

VIDEO_QUALITIES = [
    QUALITY_BEST,
    QUALITY_4K,
    QUALITY_1440P,
    QUALITY_1080P,
    QUALITY_720P,
    QUALITY_480P,
    QUALITY_360P
]

# ===== AUDIO CODECS =====
CODEC_MP3 = "MP3"
CODEC_AAC = "AAC"
CODEC_FLAC = "FLAC"
CODEC_OPUS = "Opus"
CODEC_M4A = "M4A"
CODEC_WAV = "WAV"
CODEC_ALAC = "ALAC"
CODEC_OGG = "OGG Vorbis"

AUDIO_CODECS = [CODEC_MP3, CODEC_AAC, CODEC_FLAC, CODEC_OPUS, CODEC_M4A, CODEC_WAV, CODEC_ALAC, CODEC_OGG]

# ===== AUDIO QUALITY BITRATES =====
BITRATE_320 = "320 kbps"
BITRATE_256 = "256 kbps"
BITRATE_192 = "192 kbps"
BITRATE_128 = "128 kbps"
BITRATE_96 = "96 kbps"
BITRATE_LOSSLESS = "Lossless"

AUDIO_BITRATES = [BITRATE_LOSSLESS, BITRATE_320, BITRATE_256, BITRATE_192, BITRATE_128, BITRATE_96]

# ===== VIDEO CONTAINER FORMATS =====
CONTAINER_MP4 = "MP4"
CONTAINER_MKV = "MKV"
CONTAINER_WEBM = "WebM"
CONTAINER_AVI = "AVI"
CONTAINER_MOV = "MOV"
CONTAINER_FLV = "FLV"

VIDEO_CONTAINERS = [CONTAINER_MP4, CONTAINER_MKV, CONTAINER_WEBM, CONTAINER_AVI, CONTAINER_MOV, CONTAINER_FLV]

# ===== FILENAME TEMPLATE TAGS =====
TAG_TITLE = "title"
TAG_UPLOADER = "uploader"
TAG_QUALITY = "quality"
TAG_FORMAT = "format"
TAG_WEBSITE = "website"
TAG_ID = "id"
TAG_UPLOAD_DATE = "upload_date"
TAG_DOWNLOAD_DATE = "download_date"
TAG_DURATION = "duration"
TAG_EXT = "ext"

FILENAME_TAGS = {
    TAG_TITLE: 'Title',
    TAG_UPLOADER: 'Uploader',
    TAG_QUALITY: 'Quality',
    TAG_FORMAT: 'Format',
    TAG_WEBSITE: 'Website',
    TAG_ID: 'Video ID',
    TAG_UPLOAD_DATE: 'Upload Date',
    TAG_DOWNLOAD_DATE: 'Timestamp',
    TAG_DURATION: 'Duration',
    TAG_EXT: 'Extension'
}

# Default filename template tags
DEFAULT_FILENAME_TAGS = [TAG_TITLE, TAG_QUALITY, TAG_UPLOADER]
